name = "rli"
main = "index.js"
compatibility_date = "2026-05-12"

[assets]
directory = ".."
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "rli-panel-db"
database_id = "d5a75976-7b89-4720-a619-aaff2ad81485"
