name = "rli"
main = "index.js"
compatibility_date = "2026-05-12"

[assets]
directory = ".."
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "rli-panel-db"
database_id = "REEMPLAZA_CON_EL_DATABASE_ID_DE_D1"
